# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

parameters:
#    parameter_name: value

services:
    app.controller.contact:
        class: AppBundle\Controller\ContactController
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: controller.service_arguments }

    doctrine.orm.entity_manager:
        class: Doctrine\ORM\EntityManagerInterface
        factory: ['Doctrine\ORM\EntityManager', 'create']
        arguments:
            - '%doctrine.dbal.connection_factory.class%'
            - { dbname: '%database_name%'}
        synthetic: true
